site_name: AA2FTS
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  #name: material

nav:
  - 'index.md'
  - Theory: "theory/index.md"
  - Installation: 'logistics.md'
  - Best Practices: "tutorials/bestpractices.md"
  - Case Studies: 'tutorials/index.md'
  - Running Simulations: "simulations.md"
  - References: 'publications.md'
  #- API reference
  #- Misc (how to edit these pages):
  #  - 'help.md'
  #  - 'sandbox.ipynb'
#  - MD: 'md'
#  - CG: 'cg'
#  - Field Theory: 'fieldtheory'
shortcuts:
  help: 191    # ?
  next: 78     # n
  previous: 80 # p
  search: 83   # s
plugins:
  - mkdocs-jupyter
  - bibtex:
      bib_file: "docs/references.bib"
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
